// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "goa-sample": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/hiroykam/goa-sample/design
// --out=$(GOPATH)/src/github.com/hiroykam/goa-sample
// --version=v1.3.1

package app

import (
	"fmt"
	"strings"
)

// SamplesHref returns the resource href.
func SamplesHref(id interface{}) string {
	paramid := strings.TrimLeftFunc(fmt.Sprintf("%v", id), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/api/v1/samples/%v", paramid)
}
