// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "goa-sample": Application User Types
//
// Command:
// $ goagen
// --design=github.com/hiroykam/goa-sample/design
// --out=$(GOPATH)/src/github.com/hiroykam/goa-sample
// --version=v1.3.1

package app
